fix: 修复出现指向自己的软链时会导致core问题
actboy168/bee.lua pull request #35
Opened 2023-03-04 05:16 UTC by zhanlangorz

出现一个软链指向自己时，当这个软链指向的目录有效时， 在m_recursive为true时， 会进入死循环， 最后导致目录层级过多core.
当这个软链无效时， 读取status()不加ec会直接出现Too many levels of symbolic links错误

2023-03-04 13:35 UTC, actboy168 requested changes

2023-03-04 13:35 UTC, actboy168 commented on bee/filewatch/filewatch_linux.cpp
> +            if (fs::is_directory(m_follow_symlinks? iter->status(ec): iter->symlink_status(ec))) {
status出错不应该影响继续遍历后续的文件。

2023-03-04 13:35 UTC, zhanlangorz commented
已收到!

2023-03-04 13:36 UTC, actboy168 requested changes

2023-03-04 13:36 UTC, actboy168 commented on bee/filewatch/filewatch_linux.cpp
> +            // 即该path已经监听过, 忽略不继续
不需要中文注释

2023-03-05 05:46 UTC, zhanlangorz commented on bee/filewatch/filewatch_linux.cpp
> +            // 即该path已经监听过, 忽略不继续
已清除。

2023-03-05 05:47 UTC, zhanlangorz commented on bee/filewatch/filewatch_linux.cpp
> +            if (fs::is_directory(m_follow_symlinks? iter->status(ec): iter->symlink_status(ec))) {
已处理。 加了一个新的file_status_ec.  该ec只用来防止exception

2023-03-05 06:19 UTC, actboy168 commented
不错，谢谢。

2023-03-05 06:20 UTC, merged