增加指向自己的空软链和指向父目录的目录软链测试用例
actboy168/bee.lua pull request #36
Opened 2023-03-05 07:04 UTC by zhanlangorz

增加了修复问题的测试用例， 在修复前的版本里,   跑这两个用例会直接core掉.

2023-03-05 13:36 UTC, actboy168 commented
首先请rebase到master。

2023-03-05 13:40 UTC, actboy168 requested changes

2023-03-05 13:40 UTC, actboy168 commented on test/test_filewatch.lua
> +        fs.create_symlink(test_root / 'test1', test_root/'test1')
需要检查当前平台是否支持symlink，才能用fs.create_symlink。具体请看fs.create_symlink的test

2023-03-05 13:40 UTC, actboy168 commented on test/test_filewatch.lua
> +        fw:add(test_root:string())
test已经创建了一个watch，把他改为fw:set_follow_symlinks(true)就行，没必要在这里再创建一个

2023-03-05 13:40 UTC, actboy168 commented on test/test_filewatch.lua
> +        pcall(fs.remove_all, test_root/'*')
意义不明的一行

2023-03-06 03:24 UTC, zhanlangorz commented on test/test_filewatch.lua
> +        pcall(fs.remove_all, test_root/'*')
已处理

2023-03-06 03:26 UTC, zhanlangorz commented
还有一个问题就是supportedSymlink这个函数重复了， 有必要的话可以提到公共文件里。

2023-03-06 05:37 UTC, actboy168 requested changes

2023-03-06 05:37 UTC, actboy168 commented on test/test_filewatch.lua
> +        fw:add(test_root:string())
把这两行去了，然后把test函数里的set_follow_symlinks改成true就行

2023-03-06 06:20 UTC, zhanlangorz commented on test/test_filewatch.lua
> +        fw:add(test_root:string())
done

2023-03-06 06:42 UTC, merged